### ISSUE TITLE
Use official API

### ISSUE THREAD

**Issue by pksunkara** [jianyuan/terraform-provider-openai#28]
Hey,

OpenAI has now provided official API endpoints for administration. https://platform.openai.com/docs/api-reference/administration

Can you please use that API instead of the internal API?

Also, I think `openai_project_api_key` needs to be renamed to `openai_project_service_account` instead according to the official API.

**Comment by jianyuan** [comment]
Thanks @pksunkara. I am making the adjustments now.

**Comment by jianyuan** [comment]
Implemented in [v0.3.0](https://github.com/jianyuan/terraform-provider-openai/releases/tag/v0.3.0).
